### ISSUE TITLE
About the pretrained model

### ISSUE THREAD

**Issue by jm-R152** [FangGet/Swin-Transformer#1]
Thank you for your contribution. Could you point out how can you implement the pretrained model? Very appreciate if you can help me.

**Comment by FangGet** [comment]
What do you mean by "implement"? if you'd like to evaluate, see [https://github.com/microsoft/Swin-Transformer/blob/main/get_started.md](https://github.com/microsoft/Swin-Transformer/blob/main/get_started.md)
